# Generated by Django 3.2.16 on 2023-02-15 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=100, unique=True)),
                ('interval_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('enabled', models.BooleanField(default=True)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
