# Generated by Django 4.1.7 on 2023-02-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_scheduled_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='last_runtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
