# Generated by Django 3.2.18 on 2023-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_scheduled_tasks', '0002_scheduledtask_last_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='onstart',
            field=models.BooleanField(default=False),
        ),
    ]
