# Generated by Django 4.2.10 on 2024-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_scheduled_tasks', '0003_scheduledtask_onstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='exclusive',
            field=models.BooleanField(default=True),
        ),
    ]
