# Generated by Django 4.2.18 on 2025-05-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_scheduled_tasks', '0004_scheduledtask_exclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='last_runtime',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='last_success',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='last_timestamp',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='next_expected_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='ScheduledTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('success', models.BooleanField(null=True)),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_scheduled_tasks.scheduledtask')),
            ],
        ),
    ]
