# Generated by Django 5.0.7 on 2024-08-23 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_scheduled_tasks', '0004_scheduledtask_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='day',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='hour',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='interval_minutes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
